#!/bin/sh

echo "\n DO APT UPDATE \n"
sudo apt update
echo "\n UPDATE DONE! \n"
echo "\n DO APT UPGRADE -Y \n"
sudo apt upgrade -y
echo "\n DONE! \n"
echo "\n DO APT AUTOREMOVE - Y\n"
sudo apt autoremove -y
echo "\n DONE! \n"
echo "\n FINISHED!!!!!!!!!! \n"
